name: Mana
description: Controls the flow of magic
author: RypoFalem
version: 0.1
main: io.github.rypofalem.mana.ManaPlugin
depend: [ ActionBarAPI ]
commands:
  mana:
    description: basic mana info
    usage: "/<command> - shows mana info"
    permission: mana.basic
permissions:
  mana.admin:
    description: admin stuff
    default: OP
  mana.basic:
    description: basic stuff
    default: OP